[build]
command = """
    curl -s https://get.sdkman.io | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"

    sdk install java 17.0.10-tem
    sdk use java 17.0.10-tem

    java -version

    ./gradlew :composeApp:wasmJsBrowserDistribution --stacktrace --info
  """
publish = "composeApp/build/dist/wasmJs/productionExecutable"